ALTER TABLE creator
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL,
    MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL;

ALTER TABLE brand_deal
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL,
    MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL;

ALTER TABLE expense
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL,
    MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL;

ALTER TABLE invoice
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL,
    MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL;

ALTER TABLE invoice_payment
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL,
    MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL;
